
package banksoal;

import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import java.util.Calendar;
import java.sql.Date;
import java.util.HashMap;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alice002
 */
public class Exam extends javax.swing.JInternalFrame {
    private DefaultTableModel dtm;
    Connection con;
    PreparedStatement stat;
    Statement stmt;
    ResultSet rs;
    String sql;
    String name;
    private HashMap componentMap;
    int total = 0;

    public Exam() {
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        initComponents();
        
        try {
            con = DriverManager.getConnection("jdbc:sqlserver://localhost;"
            + "databaseName=BankSoal_db;user=sa;password=root");
            
            stmt = con.createStatement();
        } catch(SQLException x) {
            System.out.println(x.toString());
        }
        
        //RandomSoal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name_text = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        soal1 = new javax.swing.JLabel();
        A_soal1 = new javax.swing.JRadioButton();
        B_soal1 = new javax.swing.JRadioButton();
        C_soal1 = new javax.swing.JRadioButton();
        D_soal1 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        soal2 = new javax.swing.JLabel();
        A_soal2 = new javax.swing.JRadioButton();
        B_soal2 = new javax.swing.JRadioButton();
        C_soal2 = new javax.swing.JRadioButton();
        D_soal2 = new javax.swing.JRadioButton();
        B_soal3 = new javax.swing.JRadioButton();
        C_soal3 = new javax.swing.JRadioButton();
        D_soal3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        soal3 = new javax.swing.JLabel();
        A_soal3 = new javax.swing.JRadioButton();
        soal4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        A_soal4 = new javax.swing.JRadioButton();
        B_soal4 = new javax.swing.JRadioButton();
        C_soal4 = new javax.swing.JRadioButton();
        D_soal4 = new javax.swing.JRadioButton();
        soal5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        A_soal5 = new javax.swing.JRadioButton();
        B_soal5 = new javax.swing.JRadioButton();
        C_soal5 = new javax.swing.JRadioButton();
        D_soal5 = new javax.swing.JRadioButton();
        soal6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        A_soal6 = new javax.swing.JRadioButton();
        B_soal6 = new javax.swing.JRadioButton();
        C_soal6 = new javax.swing.JRadioButton();
        D_soal6 = new javax.swing.JRadioButton();
        soal7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        A_soal7 = new javax.swing.JRadioButton();
        B_soal7 = new javax.swing.JRadioButton();
        C_soal7 = new javax.swing.JRadioButton();
        D_soal7 = new javax.swing.JRadioButton();
        soal8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        A_soal8 = new javax.swing.JRadioButton();
        B_soal8 = new javax.swing.JRadioButton();
        C_soal8 = new javax.swing.JRadioButton();
        D_soal8 = new javax.swing.JRadioButton();
        soal9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        A_soal9 = new javax.swing.JRadioButton();
        B_soal9 = new javax.swing.JRadioButton();
        C_soal9 = new javax.swing.JRadioButton();
        D_soal9 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        soal10 = new javax.swing.JLabel();
        A_soal10 = new javax.swing.JRadioButton();
        B_soal10 = new javax.swing.JRadioButton();
        C_soal10 = new javax.swing.JRadioButton();
        D_soal10 = new javax.swing.JRadioButton();

        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(800, 550));

        name_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                name_textKeyPressed(evt);
            }
        });

        jLabel1.setText("Nama :");

        jButton1.setText("Submit Exam!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(782, 1500));

        jLabel3.setText("1.");

        soal1.setText("soal1");

        A_soal1.setText("soal1_A");

        B_soal1.setText("soal1_B");

        C_soal1.setText("soal1_C");

        D_soal1.setText("soal1_D");

        jLabel4.setText("2.");

        soal2.setText("soal1");

        A_soal2.setText("soal1_A");

        B_soal2.setText("soal1_B");

        C_soal2.setText("soal1_C");

        D_soal2.setText("soal1_D");

        B_soal3.setText("soal1_B");

        C_soal3.setText("soal1_C");

        D_soal3.setText("soal1_D");

        jLabel5.setText("3.");

        soal3.setText("soal1");

        A_soal3.setText("soal1_A");

        soal4.setText("soal1");

        jLabel6.setText("4.");

        A_soal4.setText("soal1_A");

        B_soal4.setText("soal1_B");

        C_soal4.setText("soal1_C");

        D_soal4.setText("soal1_D");

        soal5.setText("soal1");

        jLabel7.setText("5.");

        A_soal5.setText("soal1_A");

        B_soal5.setText("soal1_B");

        C_soal5.setText("soal1_C");

        D_soal5.setText("soal1_D");

        soal6.setText("soal1");

        jLabel8.setText("6.");

        A_soal6.setText("soal1_A");

        B_soal6.setText("soal1_B");

        C_soal6.setText("soal1_C");

        D_soal6.setText("soal1_D");

        soal7.setText("soal1");

        jLabel9.setText("7.");

        A_soal7.setText("soal1_A");

        B_soal7.setText("soal1_B");

        C_soal7.setText("soal1_C");

        D_soal7.setText("soal1_D");

        soal8.setText("soal1");

        jLabel10.setText("8.");

        A_soal8.setText("soal1_A");

        B_soal8.setText("soal1_B");

        C_soal8.setText("soal1_C");

        D_soal8.setText("soal1_D");

        soal9.setText("soal1");

        jLabel11.setText("9.");

        A_soal9.setText("soal1_A");

        B_soal9.setText("soal1_B");

        C_soal9.setText("soal1_C");

        D_soal9.setText("soal1_D");

        jLabel12.setText("10.");

        soal10.setText("soal1");

        A_soal10.setText("soal1_A");

        B_soal10.setText("soal1_B");

        C_soal10.setText("soal1_C");

        D_soal10.setText("soal1_D");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_soal1)
                            .addComponent(C_soal1)
                            .addComponent(B_soal1)
                            .addComponent(A_soal1)
                            .addComponent(soal1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_soal2)
                            .addComponent(C_soal2)
                            .addComponent(B_soal2)
                            .addComponent(A_soal2)
                            .addComponent(soal2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(A_soal3)
                            .addComponent(soal3)
                            .addComponent(D_soal3)
                            .addComponent(C_soal3)
                            .addComponent(B_soal3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_soal4)
                            .addComponent(C_soal4)
                            .addComponent(B_soal4)
                            .addComponent(A_soal4)
                            .addComponent(soal4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B_soal5)
                            .addComponent(A_soal5)
                            .addComponent(soal5)
                            .addComponent(D_soal5)
                            .addComponent(C_soal5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_soal6)
                            .addComponent(C_soal6)
                            .addComponent(B_soal6)
                            .addComponent(A_soal6)
                            .addComponent(soal6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B_soal7)
                            .addComponent(A_soal7)
                            .addComponent(soal7)
                            .addComponent(D_soal7)
                            .addComponent(C_soal7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_soal8)
                            .addComponent(C_soal8)
                            .addComponent(B_soal8)
                            .addComponent(A_soal8)
                            .addComponent(soal8)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_soal9)
                            .addComponent(C_soal9)
                            .addComponent(B_soal9)
                            .addComponent(A_soal9)
                            .addComponent(soal9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_soal10)
                            .addComponent(C_soal10)
                            .addComponent(B_soal10)
                            .addComponent(A_soal10)
                            .addComponent(soal10))))
                .addContainerGap(687, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(soal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(A_soal1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B_soal1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(C_soal1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(D_soal1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(soal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(A_soal2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B_soal2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(C_soal2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(D_soal2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(soal3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(A_soal3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B_soal3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(C_soal3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(D_soal3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(soal4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(A_soal4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B_soal4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(C_soal4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(D_soal4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(soal5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(A_soal5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B_soal5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(C_soal5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(D_soal5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(soal6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(A_soal6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B_soal6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(C_soal6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(D_soal6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(soal7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(A_soal7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B_soal7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(C_soal7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(D_soal7)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(soal8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(A_soal8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B_soal8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(C_soal8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(D_soal8)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(soal9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(A_soal9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B_soal9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(C_soal9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(D_soal9)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(soal10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(A_soal10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B_soal10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(C_soal10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(D_soal10)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name_textKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_textKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER && name_text.getText().isEmpty() == false) {
            if (name_text.getText().length() <= 20) {
                name = name_text.getText();
                name_text.enable(false);                       
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Nama tidak boleh lebih dari 20 karakter!");
            }
        }
    }//GEN-LAST:event_name_textKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if (A_soal1.isSelected()) {
            total++;
        }
        
        if (B_soal2.isSelected()) {
            total++;
        }
        
        if (C_soal3.isSelected()) {
            total++;
        }
        
        if (D_soal4.isSelected()) {
            total++;
        }
        
        if (D_soal5.isSelected()) {
            total++;
        }
        
        if (C_soal6.isSelected()) {
            total++;
        }
        
        if (B_soal7.isSelected()) {
            total++;
        }
        
        if (A_soal8.isSelected()) {
            total++;
        }
        
        if (C_soal9.isSelected()) {
            total++;
        }
        
        if (D_soal10.isSelected()) {
            total++;
        }
        
        total = (total * 10)/10;
        
        try {
            Date d = new Date(System.currentTimeMillis());
            
            stat = con.prepareStatement("INSERT INTO " 
                    + "dbo.Highscore(Nama,Score,Date)" 
                    + "VALUES(?,?,?)");
            
            stat.setString(1,name_text.getText());
            stat.setInt(2,total);
            stat.setDate(3, (java.sql.Date) d);
            
            stat.executeUpdate();
            
            JOptionPane.showMessageDialog(rootPane, "Data berhasil dimasukkan");
        } catch (Exception x) {
            System.out.println(x.toString());
            JOptionPane.showMessageDialog(rootPane, "Data tidak dapat dimasukkan");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    void RandomSoal(){
        Random rand = new Random();

        int  n = rand.nextInt(56) + 1;
        int count = 0;
        
        dtm = new DefaultTableModel();                        
        
        try {
            while(count < 5){
                n = rand.nextInt(55) + 0;
                stmt = con.createStatement();       
                stat = con.prepareStatement("SELECT * FROM dbo.Soal WHERE ID=?");
                stat.setInt(1, n);
                rs = stat.executeQuery();
                
                while(rs.next()) {
                    JLabel soal;
                    String str = Integer.toString(count+1);
                    String varsoal = "soal"+str;
                    System.out.println(varsoal);
                    //if (componentMap.containsKey(varsoal)) {
                        soal = (JLabel) componentMap.get(varsoal);
                        
                        soal.setText(rs.getString("Soal"));
                    //}    
                }
                rs.close();
                                                  
                count++;
            }            
            rs.close();
            stmt.close();
        } catch(SQLException x) {
            System.out.println(x.toString());
        } 
    }
    
    
    /*
    private void createComponentMap() {
        componentMap = new HashMap<String,Component>();
        Component[] components = this.getContentPane().getComponents();
        for (int i=0; i < components.length; i++) {
                componentMap.put(components[i].getName(), components[i]);
        }
    }
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A_soal1;
    private javax.swing.JRadioButton A_soal10;
    private javax.swing.JRadioButton A_soal2;
    private javax.swing.JRadioButton A_soal3;
    private javax.swing.JRadioButton A_soal4;
    private javax.swing.JRadioButton A_soal5;
    private javax.swing.JRadioButton A_soal6;
    private javax.swing.JRadioButton A_soal7;
    private javax.swing.JRadioButton A_soal8;
    private javax.swing.JRadioButton A_soal9;
    private javax.swing.JRadioButton B_soal1;
    private javax.swing.JRadioButton B_soal10;
    private javax.swing.JRadioButton B_soal2;
    private javax.swing.JRadioButton B_soal3;
    private javax.swing.JRadioButton B_soal4;
    private javax.swing.JRadioButton B_soal5;
    private javax.swing.JRadioButton B_soal6;
    private javax.swing.JRadioButton B_soal7;
    private javax.swing.JRadioButton B_soal8;
    private javax.swing.JRadioButton B_soal9;
    private javax.swing.JRadioButton C_soal1;
    private javax.swing.JRadioButton C_soal10;
    private javax.swing.JRadioButton C_soal2;
    private javax.swing.JRadioButton C_soal3;
    private javax.swing.JRadioButton C_soal4;
    private javax.swing.JRadioButton C_soal5;
    private javax.swing.JRadioButton C_soal6;
    private javax.swing.JRadioButton C_soal7;
    private javax.swing.JRadioButton C_soal8;
    private javax.swing.JRadioButton C_soal9;
    private javax.swing.JRadioButton D_soal1;
    private javax.swing.JRadioButton D_soal10;
    private javax.swing.JRadioButton D_soal2;
    private javax.swing.JRadioButton D_soal3;
    private javax.swing.JRadioButton D_soal4;
    private javax.swing.JRadioButton D_soal5;
    private javax.swing.JRadioButton D_soal6;
    private javax.swing.JRadioButton D_soal7;
    private javax.swing.JRadioButton D_soal8;
    private javax.swing.JRadioButton D_soal9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name_text;
    private javax.swing.JLabel soal1;
    private javax.swing.JLabel soal10;
    private javax.swing.JLabel soal2;
    private javax.swing.JLabel soal3;
    private javax.swing.JLabel soal4;
    private javax.swing.JLabel soal5;
    private javax.swing.JLabel soal6;
    private javax.swing.JLabel soal7;
    private javax.swing.JLabel soal8;
    private javax.swing.JLabel soal9;
    // End of variables declaration//GEN-END:variables
}
